name: "Primary Build"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ v* ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Execute Tests (${{ matrix.os }}, Java ${{ matrix.java }})
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17, 21 ]
        os: [ ubuntu-24.04, windows-2025, macos-15, macos-13 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          check-latest: true

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Execute SBT Scripted Tests
        run: sbt scripted

      - name: Package Project Products
        run: sbt package

  publish:
    name: Publish Release
    needs: [ test ]
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 11
          check-latest: true

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Import Signing Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSS_PUBLISH_USER_SIGNING_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update Signing Key Trust Level
        run: echo -e "trust\n5\ny" | gpg --batch --no-tty --command-fd 0 --edit-key ${{ secrets.OSS_PUBLISH_USER_SIGNING_KEY_ID }}

      - name: Publish Projects
        run: sbt publishSigned sonatypeBundleRelease
        env:
          PUBLISH_USER: ${{ secrets.OSS_PUBLISH_USER }}
          PUBLISH_USER_PASSPHRASE: ${{ secrets.OSS_PUBLISH_USER_PASSPHRASE }}
          SIGNING_KEY_ID: ${{ secrets.OSS_PUBLISH_USER_SIGNING_KEY_ID }}
